const STRINGS = {
  en: {
    app_title: "Brightness Manager",
    screens: "SCREENS",
    brightness: "Brightness",
    temperature: "Color Temperature",
    presets: "PRESETS",
    filter_on: "Filter Active",
    filter_off: "Filter Inactive",
    quit: "Quit",
    settings: "Settings",
    modes: "Modes",
    disable_filter: "Disable Filter",
    enable_filter: "Enable Filter",
    startup: "Start with Windows",
    language: "Language",
    active: "Active",
    passive: "Passive",
    all: "All",
    preset_day: "Day",
    preset_office: "Office",
    preset_night: "Night",
    preset_reading: "Reading",
    preset_movie: "Movie",
  },
  tr: {
    app_title: "Brightness Manager",
    screens: "EKRANLAR",
    brightness: "Parlaklık",
    temperature: "Renk Sıcaklığı",
    presets: "HAZIR MODLAR",
    filter_on: "Filtre Aktif",
    filter_off: "Filtre Pasif",
    quit: "Çıkış",
    settings: "Ayarlar",
    modes: "Modlar",
    disable_filter: "Filtreyi Kapat",
    enable_filter: "Filtreyi Aç",
    startup: "Windows ile Başlat",
    language: "Dil",
    active: "Aktif",
    passive: "Pasif",
    all: "Tümü",
    preset_day: "Gündüz",
    preset_office: "Ofis",
    preset_night: "Gece",
    preset_reading: "Okuma",
    preset_movie: "Film",
  },
  de: {
    app_title: "Brightness Manager",
    screens: "BILDSCHIRME",
    brightness: "Helligkeit",
    temperature: "Farbtemperatur",
    presets: "VOREINSTELLUNGEN",
    filter_on: "Filter Aktiv",
    filter_off: "Filter Inaktiv",
    quit: "Beenden",
    settings: "Einstellungen",
    modes: "Modi",
    disable_filter: "Filter Deaktivieren",
    enable_filter: "Filter Aktivieren",
    startup: "Mit Windows starten",
    language: "Sprache",
    active: "Aktiv",
    passive: "Inaktiv",
    all: "Alle",
    preset_day: "Tag",
    preset_office: "Büro",
    preset_night: "Nacht",
    preset_reading: "Lesen",
    preset_movie: "Film",
  },
  fr: {
    app_title: "Brightness Manager",
    screens: "ÉCRANS",
    brightness: "Luminosité",
    temperature: "Température",
    presets: "PRÉRÉGLAGES",
    filter_on: "Filtre Actif",
    filter_off: "Filtre Inactif",
    quit: "Quitter",
    settings: "Paramètres",
    modes: "Modes",
    disable_filter: "Désactiver le Filtre",
    enable_filter: "Activer le Filtre",
    startup: "Démarrer avec Windows",
    language: "Langue",
    active: "Actif",
    passive: "Inactif",
    all: "Tous",
    preset_day: "Jour",
    preset_office: "Bureau",
    preset_night: "Nuit",
    preset_reading: "Lecture",
    preset_movie: "Film",
  },
  es: {
    app_title: "Brightness Manager",
    screens: "PANTALLAS",
    brightness: "Brillo",
    temperature: "Temperatura",
    presets: "PREAJUSTES",
    filter_on: "Filtro Activo",
    filter_off: "Filtro Inactivo",
    quit: "Salir",
    settings: "Ajustes",
    modes: "Modos",
    disable_filter: "Desactivar Filtro",
    enable_filter: "Activar Filtro",
    startup: "Iniciar con Windows",
    language: "Idioma",
    active: "Activo",
    passive: "Inactivo",
    all: "Todos",
    preset_day: "Día",
    preset_office: "Oficina",
    preset_night: "Noche",
    preset_reading: "Lectura",
    preset_movie: "Película",
  },
  it: {
    app_title: "Brightness Manager",
    screens: "SCHERMI",
    brightness: "Luminosità",
    temperature: "Temperatura",
    presets: "PREIMPOSTAZIONI",
    filter_on: "Filtro Attivo",
    filter_off: "Filtro Inattivo",
    quit: "Esci",
    settings: "Impostazioni",
    modes: "Modalità",
    disable_filter: "Disattiva Filtro",
    enable_filter: "Attiva Filtro",
    startup: "Avvia con Windows",
    language: "Lingua",
    active: "Attivo",
    passive: "Inattivo",
    all: "Tutti",
    preset_day: "Giorno",
    preset_office: "Ufficio",
    preset_night: "Notte",
    preset_reading: "Lettura",
    preset_movie: "Film",
  },
  pt: {
    app_title: "Brightness Manager",
    screens: "TELAS",
    brightness: "Brilho",
    temperature: "Temperatura",
    presets: "PREDEFINIÇÕES",
    filter_on: "Filtro Ativo",
    filter_off: "Filtro Inativo",
    quit: "Sair",
    settings: "Configurações",
    modes: "Modos",
    disable_filter: "Desativar Filtro",
    enable_filter: "Ativar Filtro",
    startup: "Iniciar com Windows",
    language: "Idioma",
    active: "Ativo",
    passive: "Inativo",
    all: "Todos",
    preset_day: "Dia",
    preset_office: "Escritório",
    preset_night: "Noite",
    preset_reading: "Leitura",
    preset_movie: "Filme",
  },
  ru: {
    app_title: "Brightness Manager",
    screens: "ЭКРАНЫ",
    brightness: "Яркость",
    temperature: "Температура",
    presets: "ПРЕСЕТЫ",
    filter_on: "Фильтр Вкл",
    filter_off: "Фильтр Выкл",
    quit: "Выход",
    settings: "Настройки",
    modes: "Режимы",
    disable_filter: "Выключить Фильтр",
    enable_filter: "Включить Фильтр",
    startup: "Запускать с Windows",
    language: "Язык",
    active: "Активен",
    passive: "Неактивен",
    all: "Все",
    preset_day: "День",
    preset_office: "Офис",
    preset_night: "Ночь",
    preset_reading: "Чтение",
    preset_movie: "Кино",
  },
  ja: {
    app_title: "Brightness Manager",
    screens: "ディスプレイ",
    brightness: "明るさ",
    temperature: "色温度",
    presets: "プリセット",
    filter_on: "フィルター有効",
    filter_off: "フィルター無効",
    quit: "終了",
    settings: "設定",
    modes: "モード",
    disable_filter: "フィルター無効化",
    enable_filter: "フィルター有効化",
    startup: "Windows起動時に開始",
    language: "言語",
    active: "有効",
    passive: "無効",
    all: "すべて",
    preset_day: "昼間",
    preset_office: "オフィス",
    preset_night: "夜間",
    preset_reading: "読書",
    preset_movie: "映画",
  },
  ko: {
    app_title: "Brightness Manager",
    screens: "디스플레이",
    brightness: "밝기",
    temperature: "색온도",
    presets: "프리셋",
    filter_on: "필터 활성",
    filter_off: "필터 비활성",
    quit: "종료",
    settings: "설정",
    modes: "모드",
    disable_filter: "필터 비활성화",
    enable_filter: "필터 활성화",
    startup: "Windows 시작 시 실행",
    language: "언어",
    active: "활성",
    passive: "비활성",
    all: "전체",
    preset_day: "낮",
    preset_office: "사무실",
    preset_night: "밤",
    preset_reading: "독서",
    preset_movie: "영화",
  },
  zh: {
    app_title: "Brightness Manager",
    screens: "显示器",
    brightness: "亮度",
    temperature: "色温",
    presets: "预设",
    filter_on: "滤镜已开启",
    filter_off: "滤镜已关闭",
    quit: "退出",
    settings: "设置",
    modes: "模式",
    disable_filter: "关闭滤镜",
    enable_filter: "开启滤镜",
    startup: "开机启动",
    language: "语言",
    active: "活动",
    passive: "非活动",
    all: "全部",
    preset_day: "白天",
    preset_office: "办公",
    preset_night: "夜间",
    preset_reading: "阅读",
    preset_movie: "电影",
  },
  ar: {
    app_title: "Brightness Manager",
    screens: "الشاشات",
    brightness: "السطوع",
    temperature: "درجة الحرارة",
    presets: "الإعدادات المسبقة",
    filter_on: "الفلتر مفعل",
    filter_off: "الفلتر معطل",
    quit: "خروج",
    settings: "الإعدادات",
    modes: "الأوضاع",
    disable_filter: "تعطيل الفلتر",
    enable_filter: "تفعيل الفلتر",
    startup: "بدء مع ويندوز",
    language: "اللغة",
    active: "نشط",
    passive: "غير نشط",
    all: "الكل",
    preset_day: "نهار",
    preset_office: "مكتب",
    preset_night: "ليل",
    preset_reading: "قراءة",
    preset_movie: "فيلم",
  },
  hi: {
    app_title: "Brightness Manager",
    screens: "स्क्रीन",
    brightness: "चमक",
    temperature: "रंग तापमान",
    presets: "प्रीसेट",
    filter_on: "फ़िल्टर सक्रिय",
    filter_off: "फ़िल्टर निष्क्रिय",
    quit: "बाहर निकलें",
    settings: "सेटिंग्स",
    modes: "मोड",
    disable_filter: "फ़िल्टर बंद करें",
    enable_filter: "फ़िल्टर चालू करें",
    startup: "विंडोज़ के साथ शुरू करें",
    language: "भाषा",
    active: "सक्रिय",
    passive: "निष्क्रिय",
    all: "सभी",
    preset_day: "दिन",
    preset_office: "कार्यालय",
    preset_night: "रात",
    preset_reading: "पठन",
    preset_movie: "फ़िल्म",
  },
  nl: {
    app_title: "Brightness Manager",
    screens: "SCHERMEN",
    brightness: "Helderheid",
    temperature: "Kleurtemperatuur",
    presets: "VOORINSTELLINGEN",
    filter_on: "Filter Actief",
    filter_off: "Filter Inactief",
    quit: "Afsluiten",
    settings: "Instellingen",
    modes: "Modi",
    disable_filter: "Filter Uitschakelen",
    enable_filter: "Filter Inschakelen",
    startup: "Starten met Windows",
    language: "Taal",
    active: "Actief",
    passive: "Inactief",
    all: "Alle",
    preset_day: "Dag",
    preset_office: "Kantoor",
    preset_night: "Nacht",
    preset_reading: "Lezen",
    preset_movie: "Film",
  },
  pl: {
    app_title: "Brightness Manager",
    screens: "EKRANY",
    brightness: "Jasność",
    temperature: "Temperatura",
    presets: "PREDEFINIOWANE",
    filter_on: "Filtr Aktywny",
    filter_off: "Filtr Nieaktywny",
    quit: "Zamknij",
    settings: "Ustawienia",
    modes: "Tryby",
    disable_filter: "Wyłącz Filtr",
    enable_filter: "Włącz Filtr",
    startup: "Uruchom z Windows",
    language: "Język",
    active: "Aktywny",
    passive: "Nieaktywny",
    all: "Wszystkie",
    preset_day: "Dzień",
    preset_office: "Biuro",
    preset_night: "Noc",
    preset_reading: "Czytanie",
    preset_movie: "Film",
  },
};

const LANG_NAMES = {
  en: "English",
  tr: "Türkçe",
  de: "Deutsch",
  fr: "Français",
  es: "Español",
  it: "Italiano",
  pt: "Português",
  ru: "Русский",
  ja: "日本語",
  ko: "한국어",
  zh: "中文",
  ar: "العربية",
  hi: "हिन्दी",
  nl: "Nederlands",
  pl: "Polski",
};

function t(key, lang) {
  return (STRINGS[lang] || STRINGS.en)[key] || key;
}

window.LANG = { STRINGS, LANG_NAMES, t };
